Repository BinodNexus/GithubActionChangelog, pull requests merged in 2025-03, with the labels that each got.

#2 Update README.md
  README.md
Labels: feature

#3 Fixed Bug 2
  README.md
Labels: bug

#4 new feature added
  README.md
Labels: feature

#5 Bug fixed three
  README.md
Labels: bug

#6 Page three improvement
  README.md
Labels: improvement
